### ISSUE TITLE
Karate tests are run even if the actual build (back/front/docker) has failed

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1260]
This build shows that even though the ui build failed, and thus the dockerTagXXXX task wasn't executed, the Karate tests are run:

Link to build: https://travis-ci.com/github/opfab/operatorfabric-core/builds/223924956

This is a waste of time as the build is not going to pass anyway, and it means that the karate tests are being executed on the latest SNAPSHOT version published to DockerHub rather than on the current code, which can be misleading.

Moving the Karate tests to a separate stage or adding a condition on the success of the building phase could solve this.

**Comment by AlexGuironnetRTE** [comment]
After reading the travis documentation and [this issue](https://github.com/travis-ci/travis-ci/issues/1066) it looks like the script phase is not designed to stop when a command fails. The idea is that it is meant to contain tests, and you would want the rest of the test suite to run even if one test fails to have a complete picture of what's working or not.
There might be workarounds (see [here](https://travis-ci.community/t/multiline-script-is-running-without-errexit/7644)) but getting #1235 / OC-1667 to work would probably be neater.

**Comment by AlexGuironnetRTE** [comment]
Related issue: In [this build](See https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/232098202) the travis build went on for 2 hours (before timing out) when actually the ui tests had failed.
It happened during the night so it wasn't really a problem but it's still a waste of resources and it might be a problem if it happens when there are other builds in the queue.
