### ISSUE TITLE
Travis - move Cypress and Karate to distinct stages

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1311]
Create distinct stages or jobs for cypress and karate tests so we can see at a glance what’s wrong in a failing build, and maybe restart just the job that caused a problem.

Use workspaces so docker images can be reused for Cypress and Karate tests (https://docs.travis-ci.com/user/using-workspaces)

This will also avoid building docker images twice (once in test-sonar and once in docker stage).

If we choose to run them as separate jobs in a common “Integration tests” stage, they could run in parallel => see if it takes less time than sequentially or not.

**Comment by AlexGuironnetRTE** [comment]
Interesting link https://travis-ci.community/t/share-docker-container-between-stages-suggested-procedure-is-problematic/5448

**Comment by AlexGuironnetRTE** [comment]
I've tested it now that we can have 5 concurrent jobs (see [build](https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/241303842)) but it doesn't reduce the overall build time. Looking at the build execution I think this is because all these steps are repeated for each job and take up most of the time :
- The overhead of starting a new VM
- all the Travis initialization (load cache etc.)
- saving the cache at the end
- loading the docker images from the workspace

=> It is actually more efficient in our case to have a single stage / job with steps that execute conditionnally depending on the context (PRs etc.)
