### ISSUE TITLE
Recipients list not well positioned in conference user card 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2005]
It shall touch the recipient field : 

![image](https://user-images.githubusercontent.com/58251627/139468291-bfa3a7cb-d42c-4301-86b3-80bba7b65928.png)

**Comment by vlo-rte** [comment]
By default, the component setting "autoPosition" is set to true but it seems this doesn't work well : 
https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/449

A solution for us could be to force position to bottom and set "autoPosition" to false, but maybe it is not very user-friendly for opfab users because the recipients list is already at the bottom of the usercard screen...
