### ISSUE TITLE
To make editable the labels of the validation/edition of the Smart Notification according to the "State"

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#2127]
Dear colleagues,

As discussed on Monday during the Trinity review meeting, it would be relevant for us to be able to edit the labels of the following buttons (Smart notification) : 

![image](https://user-images.githubusercontent.com/79971866/143457048-7b78665c-9553-4771-ad99-2c17ea593200.png)
![image](https://user-images.githubusercontent.com/79971866/143457054-fcb86aa8-c02f-4e1e-81da-9a2672ad1a69.png)

Ideally, that would be possible according to the "State".

Kind regards,

**Comment by freddidierRTE** [comment]
Add in config.json in the states two new field : 
- ValidateAnswerButtonLabel
- ModfiyAnswerButtonLabel 
Modify an existing karate test to test this new fields are well saved 

if this fields are present use them  for the label of the button , otherwise , use the existing labels 

Use in example IT incident with values : Send impact / Modify impact 
Add a cypress test in src/test/cypress/cypress/integration/ResponseCard.spec.js
