### ISSUE TITLE
Error when sending usercards - Cypress / External devices docker scripts only

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#2140]
### Steps to reproduce
* Launch an OpFab instance using the config/docker/docker-compose-cypress.sh or config/docker/docker-compose-external-devices.sh
* Load configuration
* Log in using operator1
* Try to send any usercard : when clicking the "send" button, nothing happens and in the console we see the following error:

![image](https://user-images.githubusercontent.com/45459065/143593484-7d691299-1588-4d9e-a225-081c6854b362.png)

### Probable cause
There is no problem with config/docker-compose.sh so I suspect it's due to the fact that the other two use `config/docker/nginx-external-devices-cors-permissive.conf`

### TODO
* Check if it's also the case in dev mode
* Fix the nginx cors-permissive configuration

Maybe https://github.com/opfab/operatorfabric-core/issues/1806 could fix it.

**Comment by quinarygio** [comment]
I was not able to reproduce the issue as described,. I found an error, only in "docker cypress" mode, when trying to send a "Usercad Example 2/Message" user card, due to the External App not able to respond to the received card. The error on ExternalApp when trying to send response card is an " HTTP 302 MOVED PERMANENTLY" response from nginx.
