### ISSUE TITLE
Monitoring : The sort by severity doesn't work anymore

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#2171]
Monitoring screen : The sort by severity doesn't work anymore.
To help for solve the issue, the commit that causes the regression seems to be : b5d93623ca03cbe2600008185856ffb0b2991c1c

**Comment by olivierPigeon-RTE** [comment]
The problem is due to padding. Indeed, since the severity column has been shrunk, its width is smaller than padding-left and padding-right combined, which means the sort button is unreachable (see screen below).


![screen](https://user-images.githubusercontent.com/91961842/144997258-fdd02c36-7703-4129-869f-731e02ab7dc4.png)


As you can see, the width of severity column is 36 (highlighted in the green rectangle), which is empty due to both padding left and right (in red rectangle).

PS1  increasing the width of the severity column a little is not a satisfying solution because the sort button would take only a very little part of the column due to padding and the sort would be executed only by clicking the very middle of the column. The ideal would be either to find a way to remove the padding or to increase by a lot the width of the severity column (the first solution would be much better given the number of existing columns in the ag-grid)

PS2 : Here is a proof that removing the padding solves the problem (here, the padding was removed in firefox inspector, not in the code) :

![screen2](https://user-images.githubusercontent.com/91961842/144997270-ff1e3bf2-42d3-4813-8b3d-c79ddc05fb00.png)
