### ISSUE TITLE
Logrotate for nginx does not work 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2543]

**Comment by quinarygio** [comment]
The problem is that crond service is not running inside the container, so logrotate does not run.
It would be possible to start crond inside the container but his will break the best practice to have just one service per container.
One possible solution, when nginx log directory is mapped to an external volume, is to install and run logrotate in the host and send a "USR1" signal to nginx with docker command  :  docker kill --signal="USR1"  web-ui
Here I found a blog describing the solution:
https://meerkatwatch.com/blog/nginx-docker-logrotate/
