### ISSUE TITLE
Keycloack not working in dev env ? - 502 bad gateaway when trying to log in. (macOs Monteney)

### ISSUE THREAD

**Issue by kiraka42** [opfab/operatorfabric-core#2906]
Hello, 
not sure that it is an issue but 
according to the  https://opfab.github.io/documentation/current/dev_env/. tutorial to install the project in env dev 

I am trying docker compose up,  (https://opfab.github.io/documentation/current/dev_env/#_docker_dev_env)
in order to start services but then when I am trying to connect with  a test account -> operator_1 : test  (in localhost:2002) user I have a 
502 bad gateway (looping)

<img width="1291" alt="Capture d’écran 2022-04-15 à 17 41 23" src="https://user-images.githubusercontent.com/7767216/163591178-24a72167-21b5-4f8b-905d-cd18ad98f564.png">

I am using  a macOs  Monteney.
I first thought it was this issue :  https://github.com/opfab/operatorfabric-core/issues/2552 
but it isn't exactly the same

**Comment by freddidierRTE** [comment]
Hello , 

Did you execute the following commands ?  

```
cd ${OF_HOME}/config/dev
./docker-compose.sh
```

or directly : 
```
cd ${OF_HOME}/config/dev
docker-compose up -d
```
Did you start the backend as follow ? 

```
cd ${OF_HOME}
docker-compose -f ${OF_HOME}/config/dev/docker-compose.yml up -d
bin/run_all.sh start
```

**Comment by geppyz** [comment]
I've had that issue sometimes too, it was usually because the 'java' backends where not running correctly.

1. Make sure the docker containers are running (./docker-compose.sh).
2. kill all opfab java backends forcefully: `ps auwx | grep operatorfabric-core | awk {'print $2'} | xargs -I {} kill {}`
3. go to the `bin/` folder
4. (optional) run the load_environment script if you have sdkman installed: `. ./load_environment_light.sh`
5. run the run_all script: `./run_all.sh start`
6. give it a minute to get all backends started
7. try connecting again to the web-ui and see if it works

**Comment by geppyz** [comment]
Another thing, because you are running on MacOS, docker will want to use a hostname to connect to your local backend instances. Make sure to set the following environment variable:
`export MY_DOCKER_HOST=host.docker.internal`
And after that run the `./docker-compose.sh` script again in the same terminal instance.
