### ISSUE TITLE
Add option to hide the 'Sound activation' pop-up message

### ISSUE THREAD

**Issue by lhazenoot** [opfab/operatorfabric-core#3801]
If in the settings the 'sounds for cards' and 'Sound replay enabled' are activated, then there appears a 'Sound not activated' pop-up message, every time after refreshing the page. This is annoying for our users and therefore we would like to make this pop-up message optionable. Default behaviour will remain the same (the pop-up appears).

New settings will be available in web-ui.json:
- settings.showSoundActivationMessage = true

If these settings are activated:
![Sound settings](https://user-images.githubusercontent.com/91895080/200630720-ec4873a6-3b2d-4e3b-9c83-028206b71886.png)

Then this pop-up will appear after every page refresh
![Pop-up message](https://user-images.githubusercontent.com/91895080/200630724-f4e2945d-4af8-4687-a3e9-f0758fd14606.png)

**Comment by freddidierRTE** [comment]
If you remove this sound activation popup ,  you will have potentially no sound .  

Due to auto-policy in firefox and chromium based browsers, if the user does not interact with the application
sound is not activated. 

By clicking OK the user interacts with the application and activates the sound.

You can ask your user to install opfab as an application on edge  ( Menu : ... / Application / Install as an application ) . I made a few test , the sound is always activated in this mode and you have no popup 

![image](https://user-images.githubusercontent.com/58251627/200847714-bca34a36-f69a-454f-b2f5-67896e72bfd0.png)
Sorry , i have a french install 



See https://developer.chrome.com/blog/autoplay/#web-audio
See https://www.mozilla.org/en-US/firefox/66.0/releasenotes/

**Comment by lhazenoot** [comment]
@freddidierRTE Thanks for feedback! Is there another way to not see the popup every time in the Edge browser? Because it is not really workable for us to install Opfab as a app.

**Comment by freddidierRTE** [comment]
have a look to https://www.makeuseof.com/manage-autoplay-settings-microsoft-edge/

**Comment by freddidierRTE** [comment]
if you authorize your internal opfab url to auto play sound you will not see anymore the popup

**Comment by lhazenoot** [comment]
@freddidierRTE Thanks! This will work for now.

Can I close this issue?
