### ISSUE TITLE
Choose activity area on login does not take into account day mode

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#3819]
Start opfab with option   "selectActivityAreaOnLogin": true in config.json
Log to opfab 
Go in day mode
reload opfab , the select activity popup shall be in day mode

**Comment by quinarygio** [comment]
Global day/night style is set by navbar component depending if Day/Night menu is visible. If menu is visible than style is taken from user preferences, otherwise it is taken from defalt value configured in web-ui "settings.styleWhenNightDayModeDesactivated" parameter.
When starting the application the style mode is set to "Night" by default, until navbar is loaded.
Navbar is loaded after application-loading component has finisched loading, so also after ActivityAreaChoiceAfterLoginComponent.
