### ISSUE TITLE
Issue with the scrolling bar of the Card feed menu is Firefox

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#3941]
Hi OperatorFabric's colleagues,

I saw that there is a strange display of the scroll bar of the notifications in the Card Feed menu in Firefox : 

![image](https://user-images.githubusercontent.com/79971866/207614857-d3cbc120-a5fb-48e2-a074-329bec3c1abf.png)

We are using OperatorFabric 3.11.2.RELEASE and Firefox 107.0.1 (64 bits).

Kind regards,

**Comment by quinarygio** [comment]
This is due to Firefox "GTK Overlay Scrollbars" feature that has been enabled by default in recent versions (> 100).

The GTK overlay scrollbars were enabled in the previous release, [Firefox 99](https://9to5linux.com/mozilla-firefox-99-is-now-available-for-download-with-gtk-overlay-scrollbars), but not enabled by default. Mozilla added a new option in Settings > General called “Always show scrollbars”, which lets you enable or disable the GTK overlay scrollbars.
