### ISSUE TITLE
Improve menu interaction

### ISSUE THREAD

**Issue by geppyz** [opfab/operatorfabric-core#4200]
At alliander we use the menu system of OpFab quite extensively. Especially the dropdown navigational menus. 
We would like to improve the menu to be a bit more easier to use when users navigate between different menu items.
For example: if you open two dropdown menus next to eachother the will overlap. Also it would be nice if they just 'unfold' while hovering, instead of needing to click them.

A random example of this kind of behaviour: https://codepen.io/cassidoo/pen/bGbVoJQ

**Comment by lhazenoot** [comment]
@freddidierRTE Is it possible to implement a dropdown menu with the toggle icon? So that it is more clear that there are more items underneath. See photos for example.

![Uploading Scherm­afbeelding 2023-02-14 om 10.53.38.p
![Scherm­afbeelding 2023-02-14 om 10 53 32](https://user-images.githubusercontent.com/91895080/218702629-4e74abfc-a19b-4921-a681-a7835d9f3c35.png)
ng…]()

**Comment by freddidierRTE** [comment]
yes good idea !
