### ISSUE TITLE
If navigation bar menu has only one entry, show submenu anyway

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#4451]

**Comment by OlivierVoron** [comment]
We need to have a coherent main navbar menus for all the users of the application, only sub-menus are filtered depending on the rights of the user. so if the user has no right to the sub-menus, the menu is not appearing and it is the expected behaviour.
But if the user has only one sub-menu, the actual version 3.14 replace the main navbar menu by the sub-menu and we would like to keep the main menu navbar as this.

**Comment by freddidierRTE** [comment]
This behavior shall be optional , with a boolean param in the ui-menu.json : showSubMenuIfOneEntryVisible : 

Defaut value is true
